// Generated by scripts/build-proof-registry.ts. Do not edit by hand.
export const proofRegistry = {
  "cycle-double-cover": "proofs/cycle-double-cover",
} as const;

export type RegisteredProofId = keyof typeof proofRegistry;
