#!/usr/bin/env node
import { copyFile, mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";

import { loadProofPackageFromDirectory } from "../lib/proof-packages/load-package.server";
import { resolveExistingPackagePath } from "../lib/proof-packages/locations";
import { parsePublicProofIds } from "../lib/proof-packages/public-allowlist";

async function main() {
  const root = process.cwd();
  const proofsDirectory = path.join(root, "proofs");
  const output = path.join(root, "lib/proof-packages/registry.generated.ts");
  const directories = (await readdir(proofsDirectory, { withFileTypes: true }))
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();
  const includedDirectories = parsePublicProofIds(
    process.env.PUBLIC_PROOF_IDS,
    directories,
  );
  const assetRoot = path.join(root, "public", "proof-assets");
  await rm(assetRoot, { recursive: true, force: true });
  await mkdir(assetRoot, { recursive: true });

  const entries: Array<
    [
      string,
      {
        manifest: Awaited<ReturnType<typeof loadProofPackageFromDirectory>>["manifest"];
        paperPages: Awaited<ReturnType<typeof loadProofPackageFromDirectory>>["paperPages"];
        verification: Awaited<ReturnType<typeof loadProofPackageFromDirectory>>["verification"];
        leanExcerpts: Record<string, string>;
        paperAssetUrl: string;
      },
    ]
  > = [];
  for (const directory of includedDirectories) {
    try {
      const packageDirectory = path.join(proofsDirectory, directory);
      const loaded = await loadProofPackageFromDirectory(packageDirectory);
      const leanExcerpts: Record<string, string> = {};
      for (const source of loaded.manifest.mappings.flatMap((mapping) => mapping.lean)) {
        if (leanExcerpts[source.sourceId]) continue;
        const file = await resolveExistingPackagePath(packageDirectory, source.file);
        const lines = (await readFile(file, "utf8")).split(/\r?\n/);
        leanExcerpts[source.sourceId] = lines
          .slice(source.startLine - 1, source.endLine)
          .join("\n");
      }

      const pdfPath = await resolveExistingPackagePath(
        packageDirectory,
        loaded.manifest.paper.pdf,
      );
      const assetDirectory = path.join(
        root,
        "public",
        "proof-assets",
        loaded.manifest.id,
      );
      const assetName = `${loaded.paperPages.pdfSha256}.pdf`;
      await mkdir(assetDirectory, { recursive: true });
      await copyFile(pdfPath, path.join(assetDirectory, assetName));

      entries.push([
        loaded.manifest.id,
        {
          manifest: loaded.manifest,
          paperPages: loaded.paperPages,
          verification: loaded.verification,
          leanExcerpts,
          paperAssetUrl: `/proof-assets/${loaded.manifest.id}/${assetName}`,
        },
      ]);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === "ENOENT") continue;
      throw error;
    }
  }

  const ids = entries.map(([id]) => id);
  if (new Set(ids).size !== ids.length) throw new Error("Duplicate proof-package ids");

  const registry = Object.fromEntries(entries);
  await writeFile(
    output,
    [
      "// Generated by scripts/build-proof-registry.ts. Do not edit by hand.",
      'import type { RuntimeProofPackage } from "./types";',
      "",
      `export const proofRegistry = ${JSON.stringify(registry, null, 2)} satisfies Record<string, RuntimeProofPackage>;`,
      "",
      "export type RegisteredProofId = keyof typeof proofRegistry;",
      "",
    ].join("\n"),
  );
  const mode = process.env.PUBLIC_PROOF_IDS === undefined ? "local registry" : "public allowlist";
  console.log(`Validated and registered ${entries.length} proof package(s) for ${mode}.`);
}

void main();
