#!/usr/bin/env node
import { readdir, writeFile } from "node:fs/promises";
import path from "node:path";

import { loadProofPackageFromDirectory } from "../lib/proof-packages/load-package.server";

async function main() {
  const root = process.cwd();
  const proofsDirectory = path.join(root, "proofs");
  const output = path.join(root, "lib/proof-packages/registry.generated.ts");
  const directories = (await readdir(proofsDirectory, { withFileTypes: true }))
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();

  const entries: Array<[string, string]> = [];
  for (const directory of directories) {
    try {
      const loaded = await loadProofPackageFromDirectory(path.join(proofsDirectory, directory));
      entries.push([loaded.manifest.id, `proofs/${directory}`]);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === "ENOENT") continue;
      throw error;
    }
  }

  const ids = entries.map(([id]) => id);
  if (new Set(ids).size !== ids.length) throw new Error("Duplicate proof-package ids");

  const fields = entries
    .map(([id, packagePath]) => `  ${JSON.stringify(id)}: ${JSON.stringify(packagePath)},`)
    .join("\n");
  await writeFile(
    output,
    `// Generated by scripts/build-proof-registry.ts. Do not edit by hand.\nexport const proofRegistry = {\n${fields}\n} as const;\n\nexport type RegisteredProofId = keyof typeof proofRegistry;\n`,
  );
  console.log(`Validated and registered ${entries.length} proof package(s).`);
}

void main();
